// frontend/src/components/ui/label/Label.vue
<script setup lang="ts">
import { Label, type LabelProps } from 'radix-vue'
import { useAttrs } from 'vue'
import { cn } from '@/lib/utils'

const props = defineProps<LabelProps>()

const attrs = useAttrs()
</script>

<template>
  <Label
    v-bind="props"
    :class="cn(
      'text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70',
      attrs.class ?? '',
    )"
  >
    <slot />
  </Label>
</template>

// frontend/src/components/ui/Label.jsx
import React from 'react';
import * as LabelPrimitive from '@radix-ui/react-label';
import { cn } from '@/lib/utils';

const Label = React.forwardRef(({ className, ...props }, ref) => (
  <LabelPrimitive.Root
    ref={ref}
    className={cn(
      'text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70',
      className
    )}
    {...props}
  />
));

Label.displayName = LabelPrimitive.Root.displayName;

export { Label };
